name: gemini_chat_app
description: Proyecto Flutter con Riverpod 3
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navegación moderna
  go_router: ^14.2.0

  # Selección de imágenes
  image_picker: ^1.1.2

  # UI estilo chat
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2

  # Generación de UUID
  uuid: ^4.5.1

  # Cliente HTTP avanzado
  dio: ^5.4.3+1

  # Riverpod 3 (última estable conocida)
  # flutter_riverpod: ^3.3.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.1
  # riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^3.0.3
  custom_lint: 0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
